### ISSUE TITLE
Consider using "forEach" instead of "map" as its return value is not being used here.

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/EDAVisualiser#32]
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=asyncapi_EDAVisualiser&open=AYdwcYksZxfSDDTOFuLP&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=asyncapi_EDAVisualiser&open=AYdwcYksZxfSDDTOFuLP&tab=code

**Comment by ShashwatPS** [comment]
Hey @AceTheCreator i would like to work on this can you assign me this issue ?

**Comment by AceTheCreator** [comment]
@ShashwatPS we don't assign issues, please go ahead an work on it :)

**Comment by ShashwatPS** [comment]
Thanks for the reply.
