### ISSUE TITLE
Remove this commented out code.

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/EDAVisualiser#34]
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_EDAVisualiser&open=AYdwcYkeZxfSDDTOFuLO&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_EDAVisualiser&open=AYdwcYkeZxfSDDTOFuLO&tab=code

**Comment by syedzubeen** [comment]
Hey @jonaslagoni !
Can I pick this one up?

**Comment by jonaslagoni** [comment]
Yep @syedzubeen 👍
